config/routes.rb
Rails.application.routes.draw do
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :admin

  has_secure_password

  has_many :blogs

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  def new

  end
  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_path
    else
      flash.now[:error] = 'Invalid email/password'
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:success] = 'Logged out successfully'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  before_filter :is_admin

  def index
    @users = User.all
  end
  def show
    @user = User.find params[:id]
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new params[:user]
    if @user.save
      flash[:success] = "User created"
      redirect_to users_path
    else
      render :new
    end
  end
  def edit
    @user = User.find params[:id]
  end
  def update
    @user = User.find params[:id]
    if @user.update_attributes params[:user]
      flash[:success] = "User updated"
      redirect_to users_path
    else
      render :edit
    end
  end
  def destroy
    User.destroy params[:id]
    flash[:success] = "User destroyed"
    redirect_to users_path
  end

  private
    def is_admin
      redirect_to root_path, error: "You are not authorized to do that" unless current_user.admin
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def is_admin?
    signed_in? and current_user.admin?
  end

  def current_user=(user)
    @current_user = user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error_messages.html.haml
- if @user.errors.any?
  %div{id: "error_explanation"}
    .alert.alert-error
      The form contains
      = pluralize(@user.errors.count, "error") + "."
    %ul
      - @user.errors.full_messages.each do |msg|
        %li
          *
          = msg

app/views/users/_form.html.haml
= form_for @user do |f|
  = render 'error_messages', object: f.object
  %p
    = f.label :name
    = f.text_field :name
  %p
    = f.label :email
    = f.text_field :email
  %p
    = f.label :password
    = f.password_field :password
  %p
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  %p
    %label.checkbox
      = f.check_box :admin
      Admin

  %p
    = f.submit f.object.new_record? ? 'Create User' : 'Update User'
    = link_to "Cancel", users_path

app/views/users/_user.html.haml
%tr
  %td= user.name
  %td= user.email
  %td= user.admin ? 'Yes' : 'No'
  %td
    = link_to 'Edit', edit_user_path(user), class: 'btn btn-small'
    = link_to 'Delete', edit_user_path(user), class: 'btn btn-danger btn-small', data: {confirm: 'You Sure?'}

app/views/users/edit.html.haml
.admin
  %h1 Edit User
  = render 'form'

app/views/users/index.html.haml
.admin
  %h1 Manage Users
  %p= link_to 'Create User', new_user_path, class: 'btn btn-primary'
  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th Name
        %th Email
        %th Admin
        %th
    %tbody= render @users

app/views/users/new.html.haml
.admin
  %h1 Create a new user
  = render 'form'